time_tag_mapping = {
    "15-minutes-or-less": ["is_quick_meal"],
    "30-minutes-or-less": ["is_quick_meal"],
    "60-minutes-or-less": ["is_medium_time"],
    "4-hours-or-less": ["is_long_cook"],
    "1-day-or-more": ["is_long_cook"],
    "time-to-make": [],
}

difficulty_tag_mapping = {
    "3-steps-or-less": ["is_easy"],
    "5-ingredients-or-less": ["is_easy"],
    "beginner-cook": ["is_beginner_friendly"],
    "easy": ["is_easy"],
    "from-scratch": ["is_from_scratch"],
    "inexpensive": ["is_budget_friendly"],
    "no-cook": ["is_no_cook"],
    "weeknight": ["is_quick_meal"],
}


meal_type_mapping = {
    "appetizers": ["is_appetizer"],
    "appetizers-seafood": ["is_appetizer", "has_seafood"],
    "beverages": [],
    "breakfast": ["is_breakfast", "is_complete_meal"],
    "breakfast-casseroles": ["is_breakfast", "is_casserole"],
    "breakfast-eggs": ["is_breakfast", "has_eggs"],
    "breakfast-potatoes": ["is_breakfast", "has_potatoes"],
    "brunch": ["is_brunch"],
    "casseroles": ["is_casserole", "is_complete_meal"],
    "casseroles-one-dish-meal": ["is_casserole", "is_complete_meal"],
    "cocktails": [],
    "condiments-etc": [],
    "course": [],
    "desserts": ["is_dessert"],
    "desserts-easy": ["is_dessert"],
    "desserts-fruit": ["is_dessert", "has_fruit"],
    "dips": [],
    "dips-lunch-snacks": [],
    "dips-summer": [],
    "finger-food": ["is_appetizer"],
    "garnishes": [],
    "lunch": ["is_lunch", "is_complete_meal"],
    "main-dish": ["is_complete_meal"],
    "main-dish-beef": ["is_complete_meal", "has_beef"],
    "main-dish-casseroles": ["is_complete_meal", "is_casserole"],
    "main-dish-chicken": ["is_complete_meal", "has_chicken"],
    "main-dish-crock-pot": ["is_complete_meal", "is_slow_cooker"],
    "main-dish-pasta": ["is_complete_meal", "has_pasta"],
    "main-dish-pork": ["is_complete_meal", "has_pork"],
    "main-dish-seafood": ["is_complete_meal", "has_seafood"],
    "omelets-and-frittatas": ["is_breakfast", "has_eggs", "is_complete_meal"],
    "one-dish-meal": ["is_complete_meal"],
    "pancakes-and-waffles": ["is_breakfast", "is_sweet"],
    "pasta-salad": ["is_salad", "has_pasta"],
    "picnic": [],
    "pizza": ["is_complete_meal", "is_pizza"],
    "potluck": [],
    "salads": ["is_salad"],
    "sandwiches": ["is_sandwich", "is_complete_meal"],
    "side-dishes": [],
    "side-dishes-beans": [],
    "snacks": ["is_snack"],
    "snacks-kid-friendly": ["is_snack"],
    "snacks-sweet": ["is_snack", "is_sweet"],
    "soups-beans": ["is_soup", "has_beans", "is_complete_meal"],
    "soups-crock-pot": ["is_soup", "is_slow_cooker"],
    "soups-stews": ["is_soup", "is_stew"],
    "spreads": [],
}


african_cuisine_mapping = {
    "african": ["is_african"],
    "angolan": ["is_african"],
    "congolese": ["is_african"],
    "egyptian": ["is_african", "is_middle_eastern"],
    "ethiopian": ["is_african", "is_ethiopian"],
    "libyan": ["is_african", "is_middle_eastern"],
    "moroccan": ["is_african", "is_moroccan"],
    "namibian": ["is_african"],
    "nigerian": ["is_african", "is_west_african"],
    "somalian": ["is_african", "is_middle_eastern"],
    "south-african": ["is_african", "is_south_african"],
    "sudanese": ["is_african", "is_middle_eastern"],
}


asian_cuisine_mapping = {
    "asian": ["is_asian"],
    "beijing": ["is_asian", "is_chinese"],
    "cantonese": ["is_asian", "is_chinese"],
    "chinese": ["is_asian", "is_chinese"],
    "hunan": ["is_asian", "is_chinese"],
    "szechuan": ["is_asian", "is_chinese"],
    "japanese": ["is_asian", "is_japanese"],
    "korean": ["is_asian", "is_korean"],
    "thai": ["is_asian", "is_thai"],
    "vietnamese": ["is_asian", "is_vietnamese"],
    "indian": ["is_asian", "is_indian"],
    "filipino": ["is_asian"],
    "cambodian": ["is_asian"],
    "indonesian": ["is_asian"],
    "malaysian": ["is_asian"],
    "laotian": ["is_asian"],
    "mongolian": ["is_asian"],
    "nepalese": ["is_asian"],
    "pakistani": ["is_asian", "is_indian_subcontinent"],
    "iranian-persian": ["is_middle_eastern"],
    "iraqi": ["is_middle_eastern"],
    "lebanese": ["is_middle_eastern"],
    "palestinian": ["is_middle_eastern"],
    "saudi-arabian": ["is_middle_eastern"],
    "turkish": ["is_middle_eastern", "is_turkish"],
    "middle-eastern": ["is_middle_eastern"],
    "georgian": ["is_european"],
}


european_cuisine_mapping = {
    "austrian": ["is_european"],
    "belgian": ["is_european"],
    "british-columbian": ["is_north_american"],
    "czech": ["is_european"],
    "danish": ["is_european", "is_scandinavian"],
    "dutch": ["is_european"],
    "english": ["is_european", "is_british"],
    "european": ["is_european"],
    "finnish": ["is_european", "is_scandinavian"],
    "french": ["is_european", "is_french"],
    "german": ["is_european", "is_german"],
    "greek": ["is_european", "is_mediterranean", "is_greek"],
    "hungarian": ["is_european"],
    "icelandic": ["is_european", "is_scandinavian"],
    "irish": ["is_european", "is_british"],
    "italian": ["is_european", "is_mediterranean", "is_italian"],
    "norwegian": ["is_european", "is_scandinavian"],
    "polish": ["is_european"],
    "portuguese": ["is_european", "is_mediterranean"],
    "russian": ["is_european", "is_russian"],
    "scandinavian": ["is_european", "is_scandinavian"],
    "scottish": ["is_european", "is_british"],
    "spanish": ["is_european", "is_mediterranean", "is_spanish"],
    "swedish": ["is_european", "is_scandinavian"],
    "swiss": ["is_european"],
    "welsh": ["is_european", "is_british"],
}


american_cuisine_mapping = {
    "american": ["is_american"],
    "amish-mennonite": ["is_american"],
    "baja": ["is_mexican"],
    "californian": ["is_american"],
    "canadian": ["is_north_american"],
    "cajun": ["is_american"],
    "central-american": ["is_central_american"],
    "colombian": ["is_south_american"],
    "costa-rican": ["is_central_american"],
    "cuban": ["is_caribbean"],
    "guatemalan": ["is_central_american"],
    "hawaiian": ["is_american"],
    "honduran": ["is_central_american"],
    "mexican": ["is_mexican"],
    "native-american": ["is_american"],
    "north-american": ["is_north_american"],
    "oaxacan": ["is_mexican"],
    "pacific-northwest": ["is_american"],
    "pennsylvania-dutch": ["is_american"],
    "puerto-rican": ["is_caribbean"],
    "soul": ["is_american"],
    "southern-united-states": ["is_american"],
    "southwestern-united-states": ["is_american", "is_mexican"],
    "tex-mex": ["is_american", "is_mexican"],
    "argentine": ["is_south_american"],
    "brazilian": ["is_south_american", "is_brazilian"],
    "caribbean": ["is_caribbean"],
    "chilean": ["is_south_american"],
    "ecuadorean": ["is_south_american"],
    "peruvian": ["is_south_american", "is_peruvian"],
    "south-american": ["is_south_american"],
    "venezuelan": ["is_south_american"],
}


oceania_cuisine_mapping = {
    "australian": ["is_oceanian"],
    "micro-melanesia": ["is_oceanian"],
    "new-zealand": ["is_oceanian"],
    "polynesian": ["is_oceanian"],
    "south-west-pacific": ["is_oceanian"],
}


diet_nutrition_mapping = {
    "dairy-free": ["is_dairy_free"],
    "diabetic": [],
    "egg-free": ["is_egg_free"],
    "free-of-something": [],
    "gluten-free": ["is_gluten_free"],
    "gluten-free-appetizers": ["is_gluten_free"],
    "healthy": ["is_healthy"],
    "healthy-2": ["is_healthy"],
    "high-calcium": ["is_high_calcium"],
    "high-fiber": ["is_high_fiber"],
    "high-in-something": [],
    "high-in-something-diabetic-friendly": [],
    "high-protein": ["is_high_protein"],
    "kosher": [],
    "lactose": [],
    "low-calorie": ["is_low_calorie"],
    "low-carb": ["is_low_carb"],
    "low-cholesterol": ["is_low_cholesterol"],
    "low-fat": ["is_low_fat"],
    "low-in-something": [],
    "low-protein": ["is_low_protein"],
    "low-saturated-fat": ["is_low_saturated_fat"],
    "low-sodium": ["is_low_sodium"],
    "no-shell-fish": [],
    "nut-free": ["is_nut_free"],
    "vegan": ["is_vegan"],
    "vegetarian": ["is_vegetarian"],
    "very-low-carbs": ["is_low_carb"],
}

meat_poultry_mapping = {
    "bacon": ["has_pork"],
    "bear": [],
    "beef": ["has_beef"],
    "beef-kidney": ["has_beef"],
    "beef-liver": ["has_beef"],
    "beef-organ-meats": ["has_beef"],
    "beef-ribs": ["has_beef"],
    "beef-sausage": ["has_beef"],
    "brisket": ["has_beef"],
    "ground-beef": ["has_beef"],
    "roast-beef": ["has_beef"],
    "steak": ["has_beef"],
    "steaks": ["has_beef"],
    "veal": ["has_beef"],
    "chicken": ["has_chicken"],
    "chicken-breasts": ["has_chicken"],
    "chicken-livers": ["has_chicken"],
    "chicken-thighs-legs": ["has_chicken"],
    "whole-chicken": ["has_chicken"],
    "wings": ["has_chicken"],
    "duck": ["has_duck"],
    "duck-breasts": ["has_duck"],
    "whole-duck": ["has_duck"],
    "ham": ["has_pork"],
    "hot-dogs": ["has_pork"],
    "pork": ["has_pork"],
    "pork-chops": ["has_pork"],
    "pork-loin": ["has_pork"],
    "pork-loins": ["has_pork"],
    "pork-ribs": ["has_pork"],
    "pork-sausage": ["has_pork"],
    "turkey": ["has_turkey"],
    "turkey-breasts": ["has_turkey"],
    "whole-turkey": ["has_turkey"],
    "deer": [],
    "elk": [],
    "goose": [],
    "lamb-sheep": [],
    "meat": [],
    "moose": [],
    "pheasant": [],
    "poultry": [],
    "quail": [],
    "rabbit": [],
    "wild-game": [],
}

seafood_mapping = {
    "bass": ["has_fish"],
    "catfish": ["has_fish"],
    "clams": ["has_shellfish"],
    "cod": ["has_fish"],
    "crab": ["has_seafood", "has_crab"],
    "crawfish": ["has_shellfish"],
    "fish": ["has_fish"],
    "fish-halibut": ["has_fish"],
    "fish-salmon": ["has_fish", "has_salmon"],
    "fish-tuna": ["has_fish", "has_tuna"],
    "freshwater-fish": ["has_fish"],
    "halibut": ["has_fish"],
    "lobster": ["has_shellfish"],
    "mahi-mahi": ["has_fish"],
    "mussels": ["has_shellfish"],
    "octopus": ["has_seafood", "has_octopus"],
    "orange-roughy": ["has_fish"],
    "oysters": ["has_shellfish"],
    "perch": ["has_fish"],
    "pickeral": ["has_fish"],
    "salmon": ["has_fish", "has_salmon"],
    "saltwater-fish": ["has_fish"],
    "scallops": ["has_shellfish"],
    "seafood": ["has_seafood"],
    "shellfish": ["has_seafood", "has_shellfish"],
    "shrimp": ["has_seafood", "has_shrimp"],
    "sole-and-flounder": ["has_fish"],
    "squid": ["has_seafood"],
    "tilapia": ["has_fish"],
    "trout": ["has_fish"],
    "tuna": ["has_fish", "has_tuna"],
    "whitefish": ["has_fish"],
}


vegetable_mapping = {
    "artichoke": ["has_vegetables"],
    "asparagus": ["has_vegetables"],
    "avocado": ["has_avocado", "has_vegetables"],
    "beans": ["has_legumes", "has_vegetables"],
    "black-beans": ["has_legumes", "has_vegetables"],
    "green-yellow-beans": ["has_legumes", "has_vegetables"],
    "lentils": ["has_legumes", "has_vegetables"],
    "chick-peas-garbanzos": ["has_legumes", "has_vegetables"],
    "bok-choys": ["has_leafy_greens", "has_vegetables"],
    "chard": ["has_leafy_greens", "has_vegetables"],
    "collard-greens": ["has_leafy_greens", "has_vegetables"],
    "greens": ["has_leafy_greens", "has_vegetables"],
    "lettuces": ["has_leafy_greens", "has_vegetables"],
    "spinach": ["has_leafy_greens", "has_vegetables"],
    "broccoli": ["has_cruciferous_vegetables", "has_vegetables"],
    "cabbage": ["has_cruciferous_vegetables", "has_vegetables"],
    "cauliflower": ["has_cruciferous_vegetables", "has_vegetables"],
    "carrots": ["has_carrots", "has_vegetables"],
    "corn": ["has_vegetables"],
    "eggplant": ["has_vegetables"],
    "mushrooms": ["has_mushrooms", "has_vegetables"],
    "onions": ["has_onions", "has_vegetables"],
    "peppers": ["has_peppers", "has_vegetables"],
    "potatoes": ["has_potatoes", "has_vegetables"],
    "yams-sweet-potatoes": ["has_potatoes", "has_vegetables"],
    "pumpkin": ["has_vegetables"],
    "soy-tofu": ["has_tofu", "has_vegetables"],
    "squash": ["has_vegetables"],
    "tomatoes": ["has_tomatoes", "has_vegetables"],
    "vegetables": ["has_vegetables"],
    "zucchini": ["has_zucchini", "has_vegetables"],
}


fruit_mapping = {
    "apples": ["has_fruit", "has_apples"],
    "bananas": ["has_fruit", "has_bananas"],
    "berries": ["has_fruit", "has_berries"],
    "blueberries": ["has_fruit", "has_berries"],
    "cranberries": ["has_fruit", "has_berries"],
    "raspberries": ["has_fruit", "has_berries"],
    "strawberries": ["has_fruit", "has_berries"],
    "cherries": ["has_fruit"],
    "grapes": ["has_fruit"],
    "kiwifruit": ["has_fruit"],
    "melons": ["has_fruit"],
    "peaches": ["has_fruit"],
    "pears": ["has_fruit"],
    "pitted-fruit": ["has_fruit"],
    "plums": ["has_fruit"],
    "citrus": ["has_fruit", "has_citrus"],
    "lemon": ["has_fruit", "has_citrus"],
    "lime": ["has_fruit", "has_citrus"],
    "limes": ["has_fruit", "has_citrus"],
    "oranges": ["has_fruit", "has_citrus"],
    "coconut": ["has_fruit", "has_coconut"],
    "mango": ["has_fruit", "has_tropical_fruit"],
    "papaya": ["has_fruit", "has_tropical_fruit"],
    "pineapple": ["has_fruit", "has_tropical_fruit"],
    "tropical-fruit": ["has_fruit", "has_tropical_fruit"],
    "peanut-butter": [],
    "pumpkin": ["has_vegetables"],
}


grains_mapping = {
    "breads": ["has_bread", "has_grains"],
    "brown-rice": ["has_rice", "has_grains"],
    "long-grain-rice": ["has_rice", "has_grains"],
    "medium-grain-rice": ["has_rice", "has_grains"],
    "rice": ["has_rice", "has_grains"],
    "short-grain-rice": ["has_rice", "has_grains"],
    "white-rice": ["has_rice", "has_grains"],
    "elbow-macaroni": ["has_pasta", "has_grains"],
    "lasagna": ["has_pasta", "has_grains"],
    "lasagne": ["has_pasta", "has_grains"],
    "macaroni-and-cheese": ["has_pasta", "has_grains"],
    "manicotti": ["has_pasta", "has_grains"],
    "pasta": ["has_pasta", "has_grains"],
    "pasta-elbow-macaroni": ["has_pasta", "has_grains"],
    "pasta-rice-and-grains-elbow-macaroni": ["has_pasta", "has_grains"],
    "pasta-shells": ["has_pasta", "has_grains"],
    "penne": ["has_pasta", "has_grains"],
    "ravioli-tortellini": ["has_pasta", "has_grains"],
    "spaghetti": ["has_pasta", "has_grains"],
    "grains": ["has_grains"],
    "pasta-rice-and-grains": ["has_grains"],
    "granola-and-porridge": ["has_grains", "has_oatmeal"],
    "oatmeal": ["has_oatmeal", "has_grains"],
    "quick-breads": ["has_bread", "has_grains"],
    "sourdough": ["has_bread", "has_grains"],
    "wheat-bread": ["has_bread", "has_grains"],
    "yeast": [],
}


dairy_eggs_mapping = {
    "butter": ["has_dairy"],
    "cheese": ["has_dairy", "has_cheese"],
    "cream": ["has_dairy"],
    "egg whites": ["has_eggs"],
    "eggs": ["has_eggs"],
    "eggs-dairy": ["has_eggs", "has_dairy"],
    "ice-cream": ["has_dairy"],
    "lime yogurt": ["has_dairy"],
    "margarine": ["has_fats"],
}


flavor_pantry_mapping = {
    "a1-sauce": ["is_savory"],
    "brown sugar": ["is_sweet"],
    "sugar": ["is_sweet"],
    "sweet-sauces": ["is_sweet"],
    "canned chipotle chiles": ["is_spicy"],
    "chili powder": ["is_spicy"],
    "spices": ["is_spicy"],
    "garlic cloves": ["is_savory"],
    "herb-and-spice-mixes": ["is_savory"],
    "marinara-sauce": ["is_savory"],
    "marinades-and-rubs": ["is_savory"],
    "savory-sauces": ["is_savory"],
    "tomato-sauce": ["is_savory"],
    "tomatoes-sauces": ["is_savory"],
    "juice and zest of": ["has_citrus"],
    "lime zest": ["has_citrus"],
    "kosher salt": ["is_salty"],
    "vegetable oil": ["has_fats"],
    "sauces": [],
    "water": [],
}


cooking_method_mapping = {
    "baking": ["is_baked"],
    "barbecue": ["is_grilled"],
    "broil": ["is_grilled"],
    "grilling": ["is_grilled"],
    "canning": [],
    "pressure-canning": [],
    "deep-fry": ["is_fried"],
    "microwave": ["is_microwaved"],
    "steam": ["is_steamed"],
    "stir-fry": ["is_stir_fry"],
    "stove-top": [],
}


equipment_mapping = {
    "bread-machine": ["is_baked"],
    "crock-pot-slow-cooker": ["is_slow_cooked"],
    "slow-cooker": ["is_slow_cooked"],
    "dehydrator": [],
    "food-processor-blender": ["is_blended"],
    "freezer": [],
    "mixer": [],
    "refrigerator": [],
    "small-appliance": [],
    "oven": ["is_baked"],
    "pressure-cooker": ["is_pressure_cooked"],
    "smoker": ["is_smoked"],
}


dish_type_mapping = {
    "bar-cookies": ["is_dessert"],
    "biscotti": ["is_dessert"],
    "brownies": ["is_dessert"],
    "cakes": ["is_dessert"],
    "candy": ["is_dessert"],
    "cheesecake": ["is_dessert"],
    "chocolate-chip-cookies": ["is_dessert"],
    "cobblers-and-crisps": ["is_dessert"],
    "coffee-cakes": ["is_dessert"],
    "cookie": ["is_dessert"],
    "cookies-and-brownies": ["is_dessert"],
    "cupcakes": ["is_dessert"],
    "fudge": ["is_dessert"],
    "key-lime-pie": ["is_dessert"],
    "lemon-cake": ["is_dessert"],
    "muffins": ["is_dessert"],
    "no-bake-cookies": ["is_dessert"],
    "peanut-butter-pie": ["is_dessert"],
    "pies": ["is_dessert"],
    "pies-and-tarts": ["is_dessert"],
    "puddings-and-mousses": ["is_dessert"],
    "scones": ["is_dessert"],
    "sugar-cookies": ["is_dessert"],
    "tarts": ["is_dessert"],
    "bean-soup": ["is_soup"],
    "beef-barley-soup": ["is_soup"],
    "bisques-cream-soups": ["is_soup"],
    "black-bean-soup": ["is_soup"],
    "chowders": ["is_soup"],
    "clear-soups": ["is_soup"],
    "mushroom-soup": ["is_soup"],
    "navy-bean-soup": ["is_soup"],
    "potato-soup": ["is_soup"],
    "tortilla-soup": ["is_soup"],
    "chili": ["is_stew"],
    "gumbo": ["is_stew"],
    "stews": ["is_stew"],
    "beef-sandwiches": ["is_sandwich"],
    "burgers": ["is_burger", "is_complete_meal"],
    "crab": ["has_seafood", "has_crab"],
    "curries": ["is_curry", "is_complete_meal"],
    "curries-indian": ["is_curry"],
    "macaroni-and-cheese": ["has_pasta", "is_complete_meal"],
    "pasta-salad": ["is_salad", "has_pasta"],
    "meatballs": ["is_complete_meal"],
    "meatloaf": ["is_complete_meal"],
    "pizza": ["is_pizza", "is_complete_meal"],
    "pot-pie": ["is_complete_meal"],
    "pot-roast": ["is_complete_meal"],
    "quiche": ["is_complete_meal"],
    "pretzels": ["is_snack"],
    "rolls-biscuits": ["has_bread"],
    "shakes": ["is_beverage"],
    "smoothies": ["is_beverage", "is_light_meal"],
    "beef-sauces": [],
    "jams-and-preserves": [],
    "jellies": [],
    "margarita": [],
    "mashed-potatoes": [],
    "punch": [],
    "salsas": [],
    "spaghetti-sauce": [],
    "stocks": [],
}


holiday_mapping = {
    "april-fools-day": [],
    "christmas": [],
    "chinese-new-year": [],
    "cinco-de-mayo": [],
    "easter": [],
    "fathers-day": [],
    "fourth-of-july": [],
    "halloween": [],
    "hanukkah": [],
    "independence-day": [],
    "kwanzaa": [],
    "labor-day": [],
    "mardi-gras-carnival": [],
    "memorial-day": [],
    "mothers-day": [],
    "new-years": [],
    "passover": [],
    "ramadan": [],
    "rosh-hashana": [],
    "rosh-hashanah": [],
    "st-patricks-day": [],
    "super-bowl": [],
    "superbowl": [],
    "thanksgiving": [],
    "valentines-day": [],
    "wedding": [],
}


season_mapping = {
    "fall": ["is_fall"],
    "seasonal": [],
    "spring": ["is_spring"],
    "summer": ["is_summer"],
    "winter": ["is_winter"],
}


lifestyle_context_mapping = {
    "birthday": [],
    "camping": [],
    "college": [],
    "comfort-food": [],
    "dinner-party": [],
    "for-large-groups": [],
    "gifts": [],
    "holiday-event": [],
    "kid-friendly": [],
    "leftovers": [],
    "picnic": [],
    "romantic": [],
    "toddler-friendly": [],
    "to-go": [],
}


serving_style_mapping = {
    "brown-bag": [],
    "finger-food": ["is_appetizer"],
    "flat-shapes": [],
    "presentation": [],
    "served-cold": ["is_served_cold"],
    "served-hot": ["is_served_hot"],
}


branded_noise_mapping = {
    "Cool Whip": [],
    "hidden-valley-ranch": [],
    "queso-for-all": [],
    "ragu-recipe-contest": [],
    "reynolds-wrap": [],
    "simply-potatoes": [],
    "simply-potatoes2": [],
}


meta_system_noise_mapping = {
    "bath-beauty": [],
    "bizarre": [],
    "celebrity": [],
    "cuisine": [],
    "dietary": [],
    "equipment": [],
    "heirloom-historical": [],
    "heirloom-historical-recipes": [],
    "homeopathy-remedies": [],
    "main-ingredient": [],
    "non-food-products": [],
    "novelty": [],
    "number-of-servings": [],
    "occasion": [],
    "preparation": [],
    "recipes": [],
    "recipies": [],
    "taste-mood": [],
    "technique": [],
}


corrupted_noise_mapping = {
    "Throw the ultimate fiesta with this sopaipillas recipe from Food.com.": [],
    "less_thansql:name_topics_of_recipegreater_than": [],
    "green food coloring recipe": [],
    "vegetable oil recipe": [],
    "white cake mix": [],
    "canned chipotle chiles": [],
    "juice and zest of": [],
}
